---
# tasks file for ansible-role-biomedit-transfers-tool

# Custom setup by distro
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Create the virtualenv and upgraded pip and setuptools
  pip:
    name:
      - setuptools==46.1.3
      - pip==20.0.2
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: "{{ _venv_command }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Uninstall biomedit-transfers (migrated to sett)
  pip:
    name: biomedit-transfers
    state: absent
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Install sett
  pip:
    name: "sett=={{ biomedit_transfers_tool_version }}"
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Add the venv binaries to PATH
  blockinfile:
    dest: /etc/profile.d/biomed_transfer_tool_path.sh
    create: yes
    owner: root
    group: root
    mode: 0644
    marker: "# {mark} CREATED WITH ANSIBLE. ADD SETT BINARIES TO PATH"
    content: |
      export PATH={{ biomedit_transfers_tool_venv_path }}/bin:$PATH
  when: biomedit_transfers_tool_add_to_path
