---
# tasks file for ansible-role-biomedit-transfers-tool

- name: Install EPEL yum repo to install pyton3.6
  yum:
    name: epel-release
    state: installed
  when: biomedit_transfers_tool_install_epel

- name: Install python3 and virtualenv from EPEL
  yum:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
      - python-setuptools  # this is required by the ansible pip module
    state: installed

- name: Create the virtualenv and upgraded pip and setuptools
  pip:
    name:
      - setuptools==46.1.3
      - pip==20.0.2
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: virtualenv-3

- name: Install the BiomedIT transfer tool
  pip:
    name: "biomedit-transfers=={{ biomedit_transfers_tool_version }}"
    extra_args: --extra-index-url https://pypi.dcc.sib.swiss/
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
