---
# tasks file for ansible-role-biomedit-transfers-tool

- name: Install EPEL yum repo to install pyton3.6
  yum:
    name: epel-release
    state: installed
  when: biomedit_transfers_tool_install_epel

- name: Install python3 and virtualenv from EPEL
  yum:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: installed

- name: Install python2-setuptools required by the ansible pip module
  yum:
    name: python-setuptools
    state: installed

- name: Install libxkbcommon-x11 . Dependency for the GUI
  yum:
    name: libxkbcommon-x11
    state: installed

- name: Create the virtualenv and upgraded pip and setuptools
  pip:
    name:
      - setuptools==46.1.3
      - pip==20.0.2
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
    virtualenv_command: virtualenv-3
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Uninstall biomedit-transfers (migrated to sett)
  pip:
    name: biomedit-transfers
    state: absent
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Install sett
  pip:
    name: "sett=={{ biomedit_transfers_tool_version }}"
    virtualenv: "{{ biomedit_transfers_tool_venv_path }}"
  environment: "{{ proxy_env if proxy_env is defined else {} }}"

- name: Add the venv binaries to PATH
  blockinfile:
    dest: /etc/profile.d/biomed_transfer_tool_path.sh
    create: yes
    owner: root
    group: root
    mode: 0644
    marker: "# {mark} CREATED WITH ANSIBLE. ADD SETT BINARIES TO PATH"
    content: |
      export PATH={{ biomedit_transfers_tool_venv_path }}/bin:$PATH
  when: biomedit_transfers_tool_add_to_path
