---

- name: RedHat | Install EPEL yum repo to install pyton3.6
  yum:
    name: epel-release
    state: installed
  when: biomedit_transfers_tool_install_epel

- name: RedHat | Install python3 and virtualenv from EPEL
  yum:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: installed

- name: RedHat | Install python2-setuptools required by the ansible pip module
  yum:
    name: python-setuptools
    state: installed

- name: RedHat | Install dependencies for the GUI
  yum:
    name:
      - libxkbcommon-x11
      - xcb-util-wm
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
    state: installed

- name: RedHat | Define virtualenv binary to use
  set_fact:
    _venv_command: "virtualenv-3"
